name: macos

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install && Update
        run: make install

      - name: Deploy
        run: make deploy
